### ISSUE TITLE
enhance how the redis client can be accessed from the application?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/hapi-redis-connection#3]
- Can we simplify the plugin by attaching the redis client to a server.app.redis property instead of adding it directly to the request object. From the [server.app Hapi documentation](http://hapijs.com/api#serverapp)  seems to be a more logic place to add the redisClient: "Provides a safe place to store server-specific run-time application data"

- At the moment the redisClient is [attached](https://github.com/dwyl/hapi-redis-connection/blob/f40a082426a30baa9fc6721655bf0d50c02cdf1a/index.js#L7) with the extension point "onPreAuth". This means that for each requests received by the server we are [assigning again](https://github.com/dwyl/hapi-redis-connection/blob/f40a082426a30baa9fc6721655bf0d50c02cdf1a/index.js#L15) the redis client to the property "request.redis". It also I think why we use the variable ["run_once"](https://github.com/dwyl/hapi-redis-connection/blob/f40a082426a30baa9fc6721655bf0d50c02cdf1a/index.js#L8) to not attached at each requests the [server.on('stop') event](https://github.com/dwyl/hapi-redis-connection/blob/f40a082426a30baa9fc6721655bf0d50c02cdf1a/index.js#L10). 

- The redisClient is created at the top of the file, so if even if we require multiple time the plugin (I often start and stop hapi server instances in tests),  only one instance of the redisClient will still be created which can be complicated to manage.

I think the following code would improve how the plugin manage the redisClient:

```
var pkg = require('./package.json');

exports.register = function(server, options, next) {
  var redisClient = require('redis-connection')(); // require & connect if not connected yet
  server.app.redis = redisClient;
  server.on('stop', function () { // only one server.on('stop') listener
    server.app.redis.end() // we also can keep "require('redis-connection').killall()" to be sure to kill all
    server.log(['info', pkg.name], 'Redis Connection Closed');
  });
  next();
};

exports.register.attributes = {
  pkg: pkg
};
```

Would this work or is there any reasons why we want to assign the redis client on each requests?

**Comment by nelsonic** [comment]
@SimonLab ***`Yes`*** adding the `redis` to the `request` Object was just what we thought of at the time... if you want to PR a change to _re-write_ the plugin to be smarter, please do! ❤️
