### ISSUE TITLE
what is  `pkg: pkg` meaning?

### ISSUE THREAD

**Issue by TangMonk** [dwyl/hapi-redis-connection#4]
in code https://github.com/dwyl/hapi-redis-connection/blob/master/index.js#L22

**Comment by nelsonic** [comment]
Hi @TangMonk, thank you for your question! (_and welcome to DWYL!_)
the `pkg` is simply a way to `export` the data in `package.json` which we `require` on line 1: https://github.com/dwyl/hapi-redis-connection/blob/f40a082426a30baa9fc6721655bf0d50c02cdf1a/index.js#L1

Please see: https://hapijs.com/tutorials/plugins#creating-a-plugin 
And if you have any further hapi-related questions, please ask: https://github.com/dwyl/learn-hapi/issues thanks!
